apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trino
  namespace: gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/apittaa/stack_iceberg_k8s.git'
    path: infra/src/helm-charts/trino
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: 'ice-inno'
    namespace: warehouse
    server: ''
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
